### PR TITLE
Discover screen workout card adjustment

### PR DESCRIPTION
**Pull request by AlexeiGitH**
**Added menu actions:** 
- Play workout 
- Details
- Add workout to user lib

**Added label created by**
**Added button to play workout**
**Added label when workout added to user library**

### CODE REVIEW

**Comment by klymenkoo** [comment]
@AlexeiGitH do we want to have "play" option in pop-up? we already have a play button in the card...
What do you think?

**Comment by AlexeiGitH** [comment]
> @AlexeiGitH do we want to have "play" option in pop-up? we already have a play button in the card...
> What do you think?

Well I want to keep the button 100%.
Though wanted to have all the possible options in a pop up menu (Details, which is also available on a single click, Run, Add to Lib, and Share). 
If you think it's redundant I can remove details and run from the menu.

**Comment by klymenkoo** [comment]
I would keep details, add to lib and share options in pop-up. Remove play option.

**Comment by klymenkoo** [comment]
Other than that looks good.

**Pull request merged**
